name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ci-pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: ./.github/actions/setup
      
      - name: Check code
        run: |
          mise ci:check
