name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-pr-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  checks:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Mise
        uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
        with:
          version: 2025.10.19
          install: true
          cache: true
      
      - name: Get Go path
        id: go-path
        run: | 
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo "GOBIN=$(go env GOBIN)" >> $GITHUB_OUTPUT

      - name: Cache Go modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-go
        with:
          path: |
            ${{ steps.go-path.outputs.GOMODCACHE }}
            ${{ steps.go-path.outputs.GOBIN }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install Go dependencies and tools
        run: |
          go mod download
          go install tool
      
      - name: Check code
        run: |
          mise ci:check
